// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQAtIOAPsvjSc4WtVmeEtp1RsictAcGdU',
    appId: '1:505088829368:android:7f636180243b50ceb5d14d',
    messagingSenderId: '505088829368',
    projectId: 'pp191225-53185',
    storageBucket: 'pp191225-53185.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnHHR6xETXBn7iqwlWcbQ5PNSun1ZUWnU',
    appId: '1:505088829368:ios:2c61e9e0900e76f5b5d14d',
    messagingSenderId: '505088829368',
    projectId: 'pp191225-53185',
    storageBucket: 'pp191225-53185.firebasestorage.app',
    androidClientId: '505088829368-bdeenngrpir21gqedud6usr21q4e82fg.apps.googleusercontent.com',
    iosClientId: '505088829368-c0b67cid4q8qll7ebksagqhak33938sf.apps.googleusercontent.com',
    iosBundleId: 'com.thang2k6adu.pp191225',
  );

}