// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGdWXWo2_ArHBMCn87713JefT1oYbdupI',
    appId: '1:1043002656610:android:aaf903d54a4a0317598e3b',
    messagingSenderId: '1043002656610',
    projectId: 'pp191225-2a125',
    storageBucket: 'pp191225-2a125.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsFaRS8cR7VdiEk8SzhPxR3e2sdW7vPAs',
    appId: '1:1043002656610:ios:168cb0e15164bd9f598e3b',
    messagingSenderId: '1043002656610',
    projectId: 'pp191225-2a125',
    storageBucket: 'pp191225-2a125.firebasestorage.app',
    androidClientId: '1043002656610-ssnbgik02b1gkqtlbm9dvnt6t6ol6m67.apps.googleusercontent.com',
    iosClientId: '1043002656610-3pqopqdv5rog773c1imnp729ecus7kqt.apps.googleusercontent.com',
    iosBundleId: 'com.example.temp',
  );

}